# ---------- nursesexpress.menteecollege.com (React dashboard) ----------
# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name nursesexpress.menteecollege.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name nursesexpress.menteecollege.com;

    ssl_certificate     /etc/letsencrypt/live/nursesexpress.menteecollege.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nursesexpress.menteecollege.com/privkey.pem;
    include /etc/nginx/ssl-params.conf;

    root /usr/share/nginx/dashboard;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
