# nursesexpress.menteecollege.com — React dashboard
server {
    listen 80;
    server_name nursesexpress.menteecollege.com;

    root /home/andrew/server/nursesandcompanions_and_menteecollege/menteeCollegePortal/menteecollegedashboard/build;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
