   <table width="%width%" border="0" cellspacing="0" cellpadding="0" id="midDateCells">
    <tr>
     <td>
      <table width="%width%" border="0" cellspacing="0" cellpadding="1">
       <tr>
        <td colspan="7" class="monthHeader" align="center">%cell_month%</td>
       </tr>
       <tr>
        <td width="12.5%" align="center" class="header">%cell_header[1]%</td>
        <td width="12.5%" align="center" class="header">%cell_header[2]%</td>
        <td width="12.5%" align="center" class="header">%cell_header[3]%</td>
        <td width="12.5%" align="center" class="header">%cell_header[4]%</td>
        <td width="12.5%" align="center" class="header">%cell_header[5]%</td>
        <td width="12.5%" align="center" class="header">%cell_header[6]%</td>
        <td width="12.5%" align="center" class="header">%cell_header[7]%</td>
       </tr>
       <tr>
        <td width="12.5%" align="right" valign="top" class="%css_data[1]%">%cell_content[1]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[2]%">%cell_content[2]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[3]%">%cell_content[3]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[4]%">%cell_content[4]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[5]%">%cell_content[5]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[6]%">%cell_content[6]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[7]%">%cell_content[7]%</td>
       </tr>
       <tr>
        <td width="12.5%" align="right" valign="top" class="%css_data[8]%">%cell_content[8]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[9]%">%cell_content[9]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[10]%">%cell_content[10]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[11]%">%cell_content[11]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[12]%">%cell_content[12]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[13]%">%cell_content[13]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[14]%">%cell_content[14]%</td>
       </tr>
       <tr>
        <td width="12.5%" align="right" valign="top" class="%css_data[15]%">%cell_content[15]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[16]%">%cell_content[16]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[17]%">%cell_content[17]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[18]%">%cell_content[18]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[19]%">%cell_content[19]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[20]%">%cell_content[20]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[21]%">%cell_content[21]%</td>
       </tr>
       <tr>
        <td width="12.5%" align="right" valign="top" class="%css_data[22]%">%cell_content[22]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[23]%">%cell_content[23]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[24]%">%cell_content[24]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[25]%">%cell_content[25]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[26]%">%cell_content[26]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[27]%">%cell_content[27]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[28]%">%cell_content[28]%</td>
       </tr>
       <tr>
        <td width="12.5%" align="right" valign="top" class="%css_data[29]%">%cell_content[29]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[30]%">%cell_content[30]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[31]%">%cell_content[31]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[32]%">%cell_content[32]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[33]%">%cell_content[33]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[34]%">%cell_content[34]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[35]%">%cell_content[35]%</td>
       </tr>
       <tr>
        <td width="12.5%" align="right" valign="top" class="%css_data[36]%">%cell_content[36]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[37]%">%cell_content[37]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[38]%">%cell_content[38]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[39]%">%cell_content[39]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[40]%">%cell_content[40]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[41]%">%cell_content[41]%</td>
        <td width="12.5%" align="right" valign="top" class="%css_data[42]%">%cell_content[42]%</td>
       </tr>
      </table>
     </td>
    </tr>
   </table>

