   <div class="noprint">
   <div id="nav">
   <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
     <td colspan="2" align="right">%menu%</td>
    </tr>
    <tr>
     <td width="50%" valign="bottom">
      %viewModes%
     </td>
     <td width="50%" align="right">
      <br />
      %dateSelector%
     </td>
    </tr>
   </table>
   </div>
   </div>

   <div id="calnav">
   <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
     <td align="left"><div class="noprint">%miniPrev%</div></td>
     <td align="center">
      %titleNav%
     </td>
     <td align="right"><div class="noprint">%miniNext%</div></td>
    </tr>
   </table>
   </div>

   <table width="100%" border="0" cellspacing="0" cellpadding="0" id="dateCells">
    <tr>
     <td>
      <table width="100%" border="0" cellspacing="1" cellpadding="2">

       %headers%
       %cells%

      </table>
     </td>
    </tr>
   </table>