<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html %dir%>
 <head>
  <title>%title%</title>
  <meta http-equiv="pragma" content="no-cache">
  <meta http-equiv="expires" content="Wed, 27 Dec 2000 08:00:00 GMT">
  <meta http-equiv="cache-control" content="no-cache, must-revalidate">
  <meta http-equiv="Content-Type" content="text/html; charset=%charset%">
  <meta name="generator" content="BosDates 4.0 by BosDev">
  <meta name="author" content="BosDev http://www.bosdev.com">
  <link rel="stylesheet" media="screen" href="%style%" type="text/css" >
  <link rel="stylesheet" media="screen" href="%addstyle%" type="text/css" >
  <link rel="stylesheet" media="print"  href="%print%" type="text/css" >
 </head>

 <body>
 <script language="JavaScript" src="%javascript%"></script>

%event_data%

 </body>
</html>

